Poll feature
TwitchPlaysPokemon/tpp-core pull request #156
Opened 2021-01-18 20:29 UTC by Yoso2

Allows for poll voting using the 4-letter identifier. `!Vote ABCD option1 option3`
Allows multiple choice if the poll allows it.
Dev code remains for creating a poll with chat commands, but python code in tpp for creating the poll has been started

2021-01-18 22:59 UTC, Felk commented
Why does it differentiate between int options and string options?

2021-01-19 19:59 UTC, Yoso2 commented
It is to be used as a shorthand for voting. For when multi-choice polls has many long options, `!vote PKMN 1 3 5 8` would work the same as `!vote PKMN bulbasaur venosaur charmeleon wartortle` as an example.

2021-01-22 16:04 UTC, Felk requested changes
Mostly code issues, looks fine functionality-wise as far as I can judge from the code. But I'd also like there to be tests for the poll repo, like there are for the other repository implementations.

2021-01-24 22:39 UTC, Yoso2 commented on Core/Commands/Definitions/PollCommands.cs
> +            if (hasVoted) return new CommandResult { Response = $"You have already voted on poll \"{pollName}\"." };
That was the intended functionality, yes. Would letting them change their vote matter in many situations?

2021-01-24 22:41 UTC, Yoso2 commented on Core/Commands/Definitions/PollCommands.cs
> +            //    Description = "Starts a poll with single choice. Argument: <PollName> <PollCode> <Option1> <Option2> <OptionX> (optional)"
The reason this was removed in favour of the web versions is to allow for spaces to be used in names. And I agree poll title makes more sense.

2021-01-24 22:42 UTC, Yoso2 commented on Core/Commands/Definitions/PollCommands.cs
> +            //    Description = "Starts a poll with single choice. Argument: <PollName> <PollCode> <Option1> <Option2> <OptionX> (optional)"
Since creation of polls will not be a twitch command, `!poll` can be a command to get information on all or a specific poll

2021-01-27 16:43 UTC, Felk commented on Core/Commands/Definitions/PollCommands.cs
> +            if (hasVoted) return new CommandResult { Response = $"You have already voted on poll \"{pollName}\"." };
no that's fine if it's intended

2021-03-31 16:37 UTC, Felk commented
continued in https://github.com/TwitchPlaysPokemon/tpp-core/pull/217

2021-03-31 16:37 UTC, closed without merging